os: osx

language: cpp

compiler:
  - clang

before_script:
  - brew update
  - brew upgrade cmake
  - git submodule update --init --recursive
  - python get_steinberg_sdk.py
  - cmake Smexoscope

script: make
