os: osx

language: cpp

compiler:
  - clang

before_script:
  - brew update
  - brew upgrade cmake
  - git submodule update --init --recursive
  - python get_steinberg_sdk.py
  - cmake .

script: make

# before_deploy:
#   - zip -r OSX-Plugins.zip Smexoscope/Smexoscope.vst Bouncy/Bouncy.vst

# deploy:
#   provider: releases
#   skip_cleanup: true
#   api_key:
#     secure: ru62+r7ZENuAML1dhC4+URlf8/aX2WoYFCV+03Hlu2uYuuloWzWaHy+9txpL/zMXOmsCMgCrcGDQvXxIwDFt1Pw+Jc82NuzeYMbGjNkvDcVYlJgucLn7wx08ZFHYnGnLXhf2SyJ+03PzaSz9j1eHek12NujZTWQf4T3sM8vk9XbM8QM+EZEuTSkq4q1E+Ys1BFFcIHttDKHuRgvanucgPpkD07cZtswLsTkyFgWVlQfgLO6WEMdUP2zp20s86wEKjZZXI4aIUOwl/7UE3Hv3WZ5FYtrfmbK9jdhPW2QvrYtAw2YztUuP8+W4oIkVrjBKiJhKhSrO98mVUMb4z1UUF0p2gOMIZ1PxGJmvzWh55n7Ae2tBZWnFRz9p1hi5bRtwj1DzVuTKqHRrCn5Q2qKXsUvR4yshlMa506RhQgHlP86D26i76syhj0B606EF2t4fBcV/0nkdEoRn4nsrFUqTWOc7u9RxPy+kB6jxiaaP9bdbDgMAp9vYtr0WVbNgYWbgz/xbDUsSF7jCyceB19+Z6p15q2+u3sqzMIRVFx2TXQBu5TtUxBsoldGKjBPBlGyBzFmchIUGmscFyV5jFKALQKC/lIZw7+U47FbfdDpBxTgEUYYx1JtrviGdWCxt7Hmkv8Aj/bb3NrFFYcmuUAX7g1kVG0IO8c7u6dzKJ5Stb9g=
#   file: OSX-Plugins.zip
#   on:
#     tags: true
