os: Visual Studio 2015

matrix:
  fast_finish: true

platform:
  - x86
  - x64

configuration:
  - Release

before_build:
  - git submodule update --init --recursive
  - python get_steinberg_sdk.py
  - mkdir build%PLATFORM%
  - pushd build%PLATFORM%
  - if %PLATFORM% == x86 (cmake ../) else (cmake -G "Visual Studio 14 2015 Win64" ../)
  - cd..

build_script:
  - cmake --build build%PLATFORM% --config %CONFIGURATION%

deploy:
  provider: GitHub
  description: "Smexoscope Windows"
  auth_token:
    secure: xe9XPoDfnyZLB7uIULqAWtTN4kwZBnsHVv9is3AlF3q+PJn05Smyl7RRptUSZk8r
  artifact: build%PLATFORM%\Smexoscope\Release\Smexoscope.dll
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true        # deploy on tag push only
