os: Visual Studio 2015

matrix:
  fast_finish: true

platform:
  - x86
  - x64

configuration:
  - Release

before_build:
  - git submodule update --init --recursive
  - python get_steinberg_sdk.py

build_script:
  - ps: .\build.ps1 $env:PLATFORM $env:CONFIGURATION

after_build:
  - ps: 7z a Win-Plugins-$env:PLATFORM.zip .\build$env:PLATFORM\*\Release\*.dll

artifacts:
  - path: Win-Plugins-$(PLATFORM).zip
    name: Win-Plugins-$(PLATFORM)

deploy:
- provider: BinTray
  username: bdejong
  api_key:
    secure: aJrQELByJLr1WnPto6BeemIs6HjtTs3g/ewSFeYF1FZbsFfxAAgbpYTA0SSWMaX0
  subject: bdejong
  repo: Plugins
  package: Windows
  version: 1.0
  publish: true
  override: true
