os: Visual Studio 2015

matrix:
  fast_finish: true

platform:
  - x86
  - x64

configuration:
  - Release

before_build:
  - git submodule update --init --recursive
  - python get_steinberg_sdk.py
  - choco upgrade cmake
  - set path=C:\Program Files\CMake\bin;%path%

build_script:
  - ps: .\build.ps1 -Verbose $env:PLATFORM $env:CONFIGURATION

after_build:
  - ps: 7z a Win-Plugins-$env:PLATFORM-$env:APPVEYOR_BUILD_VERSION.zip .\CMakeBuild\$env:PLATFORM\*\Release\*.dll

artifacts:
  - path: Win-Plugins-$(PLATFORM)-$env:APPVEYOR_BUILD_VERSION.zip
    name: Win-Plugins-$(PLATFORM)-$env:APPVEYOR_BUILD_VERSION

deploy:
- provider: BinTray
  username: bdejong
  api_key:
    secure: aJrQELByJLr1WnPto6BeemIs6HjtTs3g/ewSFeYF1FZbsFfxAAgbpYTA0SSWMaX0
  subject: bdejong
  repo: Plugins
  package: Windows
  version: {version}
  publish: true
  override: true
