os: Visual Studio 2015

matrix:
  fast_finish: true

platform:
  - x86
  - x64

configuration:
  - Release

before_build:
  - git submodule update --init --recursive
  - python get_steinberg_sdk.py

build_script:
  - ps: .\build.ps1 %PLATFORM% %CONFIGURATION%

# artifacts:
#   - path: build$(PLATFORM)\Smexoscope\Release\Smexoscope.dll
#     name: Smexoscope-$(PLATFORM)

# deploy:
#   provider: GitHub
#   description: "Smexoscope Windows"
#   auth_token:
#     secure: xe9XPoDfnyZLB7uIULqAWtTN4kwZBnsHVv9is3AlF3q+PJn05Smyl7RRptUSZk8r
#   draft: false
#   prerelease: false
#   on:
#     appveyor_repo_tag: true
